services:

  charge-point:
    build:
      context: .
      dockerfile: Dockerfile
    image: charge-point:latest
    ports:
      - "8080-8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBIT_ADDRESS=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

  httpecho:
    hostname: httpecho.com
    image: 'mendhak/http-https-echo:35'
    ports:
      - '9999:8080'
      - '8443:8443'
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge



